# Site settings
title: Lost Weekend
email:
description: > # this means to ignore newlines until "baseurl:"
  Lost Weekend
baseurl: ""
url: "http://yourdomain.com"
twitter_username: lostweekend

# Build settings
markdown: kramdown
